printN: printn.c
	gcc printn.c -o printn

prime: primes.c
	gcc primes.c -o primes

getPrimes: printN prime
	./printn | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes | ./primes